blueprint:
  name: Zone Change Notification
  description: Send a notification to a device when a person changes zones
  domain: automation
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input person_entity

variables:
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"
  from_zone: "{{ trigger.from_state.state }}"
  to_zone: "{{ trigger.to_state.state }}"
  
  {# home zone and not_home zone are special zones in Home Assistant - with name not configurable #}
  from_zone_name: >
    {% if from_zone == "home" %} "Home"
    {% elif from_zone == "not_home" %} "away"
    {% else %} "{{ from_zone }}"
  to_zone_name: >
    {% if to_zone == "home" %} "Home"
    {% elif to_zone == "not_home" %} "away"
    {% else %} "{{ to_zone }}"

condition:
  condition: template
  # Trigger if zone changed for person
  value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"

action:
  - alias: "Notify that a person changed zone"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: "{{ person_name }} has moved from {{ from_zone_name }} to {{ to_zone_name }}"
